Ft front tests 145028641
andela/healthchecks-thunknalla pull request #5
Opened 2017-05-22 12:01 UTC by georgreen

2017-05-22 19:32 UTC, collinmutembei requested changes
👀 Still looking into this.

2017-05-22 19:32 UTC, collinmutembei commented on hc/front/views.py
> +    print("returned page")
I believe this print statement was introduced for debugging purposes. In which case you should avoid pushing code with debug statements.

2017-05-22 19:59 UTC, collinmutembei commented
Remove the square brackets on the PR title.

2017-05-23 07:06 UTC, georgreen commented on hc/front/views.py
> +    print("returned page")
done

2017-05-23 11:27 UTC, collinmutembei requested changes
@georgreen @davidmukiibi Have a look at the comments I have left and attend to them.

2017-05-23 11:27 UTC, collinmutembei commented on hc/front/tests/test_add_channel.py
> +            self.client.login(username="bob@example.org", password="password")
Do lines [51-53](https://github.com/andela/healthchecks-thunknalla/blob/a066e49909c4a8b039d53bebf7047853310afff4/hc/front/tests/test_add_channel.py#L51-L53) need to be in the for loop?

2017-05-23 11:27 UTC, collinmutembei commented on hc/front/tests/test_add_channel.py
> +            url = "/integrations/add_%s/" % any_kind
I recommend using `str.format()` for string formatting.

Resource: [pyformat.info](https://pyformat.info)

2017-05-23 11:27 UTC, collinmutembei commented on hc/front/tests/test_add_channel.py
> +            assert r.status_code == 404
Replace this assert statement with its equivalent in Django.

Resource: [Django assertions](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#assertions)

2017-05-23 11:27 UTC, collinmutembei commented on hc/front/tests/test_add_check.py
> +        assert check.timeout.total_seconds() == 5000
Use djangoish assert statements. See previous similar comment.

2017-05-23 11:27 UTC, collinmutembei commented on hc/front/tests/test_add_check.py
> +        r = self.client.post(url, data=payload)
Refrain from using variable names such as `r`. Use a descriptive name. If you find such in existing code, try to understand the context and update them to a meaningful name.

@georgreen @davidmukiibi @victoriaaoka @Andretalik @Kachulio1

2017-05-23 11:27 UTC, collinmutembei commented on hc/front/tests/test_add_pushbover.py
> +    def test_validate_priority(self):
@georgreen @davidmukiibi Could either of you explain what is going on in this test method.

2017-05-23 19:41 UTC, georgreen commented on hc/front/tests/test_add_pushbover.py
> +    def test_validate_priority(self):
@collinmutembei pushover is a service that provides a simple way to send notifications to devices from our web app, the notification sent have priority ranging from -2 to 2, this function test that we can only add pushover notification in this valid range so anything else should not be validated ie strings and integers out of range. If the user tries to add such a pushover without the correct priority the response status code should be 400 (bad request). Hope am clear enough we can expand further on our reasoning in our stand up meeting.

2017-05-23 19:52 UTC, georgreen commented on hc/front/tests/test_add_channel.py
> +            self.client.login(username="bob@example.org", password="password")
After looking at it, I think logging in once is enough and we don't need line 51 in the loop, we will move it out of the loop.

2017-05-23 19:56 UTC, collinmutembei commented on hc/front/tests/test_add_pushbover.py
> +    def test_validate_priority(self):
🆒

2017-05-25 06:10 UTC, collinmutembei commented
Looks good. Add the PR description and I'll merge.

2017-05-25 19:15 UTC, collinmutembei approved these changes

2017-05-25 19:16 UTC, merged